### ISSUE TITLE
Language Result Filter

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#10]
The filter gets extended by one section: Via a multiselect all available Languages can be selected in any combination. Firing this search will filter the search result on the selected languages (table "tour", column "text_lang").

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/ae647987-17e6-4909-9309-54f9589398a8)

**Comment by martinheppner** [comment]
![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/1790b222-a7fb-4843-a53d-cd227e5da39a)

**Comment by martinheppner** [comment]
Version 3: Mobile & Desktop: https://www.figma.com/file/qM4hoaxmGrrEEuTv4lL2lD/zuugle-redesign-2023-v3.0?type=design&node-id=0-1&t=g3UdMU8w26zmTY3s-0

**Comment by Cleatuer** [comment]
**Questions:**

1. Is there a specified set of languages that a tour can have? We would need to know, since we have to map all possible options for the frontend.

 2. You mentioned that the languages should be dynamic based on the results of the search - our assumption would be, to query all the tours for the current "Heimatbahnhof" and then display all the languages that occur for this set of tours.
**Example**: 
Graz is selected as my "Heimatbahnhof" and there are only tours in German and English for this city - the filter should only have German and English as selectable language options.
When I now apply a filter and only get German tours as my result, the filter will still have German and English as selectable options.

Would this also be your desired behavior?

**Comment by martinheppner** [comment]
I have the feeling you are overthinking this. There is the table tours. In it you find a column named "text_lang" for text language.

Do a "select distinct text_lang from tours" and you have your filter list.

The language list and the shortcodes, as well how you create the "where in ( ... )" clause for the search, will be provided by Faris.
@Falsal can you please support here? Thank you!

**Comment by martinheppner** [comment]
There is a language selection feature, which has of course nothing to do with the filter, but the languages are the same.

**Comment by Falsal** [comment]
this is related to the zuugle-api issue#10
https://github.com/bahnzumberg/zuugle-api/issues/10 

the idea of this feature could be used to adjusted so that a selection of the language in the filter would replace the primary language selected (primary in that feature is given to the menu lang and the secondary priority is given to the language of the current domain)

**Comment by Falsal** [comment]
As an example : entering zuugle.at and switching language to eng , then performing a search , i would normally get the list of all results related to the search term presented and with the first tours being in english and the second in german then the rest of the other languages.
If i then go to the filter and select "Slovenian" then i would see only results in Slovenian

with the feature "Language Result Filter," we get an additional filter applied to the already acquired results and select from them only the ones in Slovenian.
@Cleatuer  @martinheppner (Martin please confirm the accuracy of the description above)

**Comment by Falsal** [comment]
> **Questions:**
> 
> 1. Is there a specified set of languages that a tour can have? We would need to know, since we have to map all possible options for the frontend.
> 2. You mentioned that the languages should be dynamic based on the results of the search - our assumption would be, to query all the tours for the current "Heimatbahnhof" and then display all the languages that occur for this set of tours.
>    **Example**:
>    Graz is selected as my "Heimatbahnhof" and there are only tours in German and English for this city - the filter should only have German and English as selectable language options.
>    When I now apply a filter and only get German tours as my result, the filter will still have German and English as selectable options.
> 
> Would this also be your desired behavior?

@Cleatuer : so to rephrase your suggestion (to my understanding), the front end should reflect the languages with which the results are available in the table even before the user submits the filter selection?

**Comment by martinheppner** [comment]
The usecase described by @Falsal is absolutely correct.

Additionally: All filter options are already reacting to what has been searched for and filtered for. If I search for "Schneeberg" I will never see the mountain range "Hohe Tauern".

If there is no Slovenian text available, I will not see this filter option.

**Comment by Cleatuer** [comment]
All right, thanks for you clarifications - we also inspected the current filter endpoint, which - for example - also returns the tour types already in a similar way. We can just extend the implementation there for the languages 👍

---

> @Cleatuer : so to rephrase your suggestion (to my understanding), the front end should reflect the languages with which the results are available in the table even before the user submits the filter selection?

@Falsal Yes, that is what I meant. But my criteria for the selection was too complicated, since we will not return the results based on the selected city or something. Now, we will only query the tours (the way it already happens in the filter endpoint) and return the distinct languages that are found there.

**Comment by martinheppner** [comment]
Again: All filter options are already reacting to what has been searched for and filtered for. If I search for "Schneeberg" I will never see the mountain range "Hohe Tauern".

If there is no Slovenian text available, I will not see this filter option.
