### ISSUE TITLE
Use disposal Tokens for Search

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#11]
The detail page of one specific hike is https://www.zuugle.at/tour?id=33427&city=wien&sort=relevanz&datum=2023-05-18
A precondition to this issue is, that the id for one tour stays unchanged. This is not yet secured and has to be ensured in the MySQL database. Nevertheless we can implement this feature with the current state of the PostgreSQL databse.

In the future the url should be https://www.zuugle.at/tour/tr676f55fdre465drr
Internally there should be a new table, which holds the key "tr676f55fdre465drr" and datetime, till it is valid. If it is still valid, it should show the result https://www.zuugle.at/tour?id=33427&city=wien&sort=relevanzdatum=2023-05-18 would have shown. So in the table additional infornmation has to be stored.

The whole idea behind this is to hide the id of the tour and the other parameters. We want to do that to enable our vistors to share the link among friends (via social media, mail, etc). The shared link should hold exactly the day with the time table ("Fahrplan") the visitor choose. As we do not want people to link to our result page from their website and implement a cheap way for them to get access to the time table we calculated with high effort, the shared url should **expire after 20 days**.

There should be a clean up job "npm run clean-database" which will be run once a day via cronjob, which deletes all outdated links (older than 20 days).

**Comment by martinheppner** [comment]
Version 3: Mobile & Desktop: https://www.figma.com/file/qM4hoaxmGrrEEuTv4lL2lD/zuugle-redesign-2023-v3.0?type=design&node-id=0-1&t=g3UdMU8w26zmTY3s-0

**Comment by Cleatuer** [comment]
Meeting Notes from 29.06.2023:

### Detail
Link: https://www.zuugle.at/tour?id=33427&city=wien&sort=relevanz&datum=2023-05-18
This link will stay as it is - since the id is only valid for one day anyway (resets daily on import)

### Share Button
Upon clicking the share button on a detail, we generate a new ID and make a new Entry in the DB, containing the
`provider` + `hashedUrl` (which together are the Primary Key of a tour, so we can always identifiy the same tour with this information) and the `date` (and `city`?)

**Share Link:** https://www.zuugle.at/tour?share=tr34634524634534534 - date is in this ID

When calling this link, we will first make a BE call to 
`api/share/tr34634524634534534`
which gives us the current tour id of the tour. With this id we can continue to 
https://www.zuugle.at/tour?id=NEW_ID&city=wien&sort=relevanz&datum=2023-05-18
which calls api/tour/3347 again

**Comment by martinheppner** [comment]
Nicole proposed: We would (at least) need the following columns for the new table:
shareId (the generated id that will also be used in the URL)
- provider
- hashedUrl
- tourDate (the date that should be selected when opening the share link)
- city

**Comment by martinheppner** [comment]
Please add to the bottom of database.sql the following lines and reinitialize Docker again (I am deleting everything and running the two steps on the command line in the zuugle-api directory again)

1. docker build -t zuugle-postgres-db ./
2. docker run -d --name zuugle-container -p 5432:5432 zuugle-postgres-db

#########################################

CREATE TABLE disposible ( 
  provider varchar(30) NOT NULL,
  hashed_url varchar(100) NOT NULL,
  link varchar(100) NOT NULL,
  calendar_date timestamp NOT NULL,
  city_slug varchar(100)  NOT NULL
);

CREATE INDEX ON disposible (provider);
CREATE INDEX ON disposible (hashed_url);
CREATE INDEX ON disposible (link);
