### ISSUE TITLE
Meta data in HTML

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#149]
Is it translated?
Language?
Canonical

**Comment by FALBZB** [comment]
@martinheppner : 
I am just getting educated on the subject from the link you sent earlier.

here is an excerpt from the Google doc:
**_**What's the difference between multilingual and multi-regional? 
A multilingual website is any website that offers content in more than one language. For example, a Canadian business with English and French versions of its site. Google Search tries to find pages that match the language of the searcher.
A multi-regional website is one that explicitly targets users in different countries. For example, a product manufacturer that ships to both Canada and the United States. Google Search tries to find the right locale page for the searcher.
Some sites are both multi-regional and multilingual: for example, a site might have different versions for the USA and for Canada, and both French and English versions of the Canadian content.**_**

is Zuugle intention to be a multi-regional or multi-lingual ? or both? I am referring to the fact that now we have one content that we translate and we have this same content inside different domain extensions. so we are both now, do you also see it that way?

do you have more comments on this subject?

**Comment by FALBZB** [comment]
Here is another excerpt from the same page : 


What Google doesn't do:

_**Google crawls the web from different locations around the world. We do not attempt to vary the crawler source used for a single site in order to find any possible variations in a page. Therefore, make sure you explicitly tell Google about any locale or language variation that your site exposes, using one of the methods shown here (such as hreflang entries, ccTLDs, or explicit links).
Google ignores locational meta tags (like geo.position or distribution) or geotargeting HTML attributes.**_

so does this relate to our case ?

**Comment by martinheppner** [comment]
Sure it does. This metadata issue touches the translation of the index page. So if I open up www.zuugle.at the description should always be in German, but www.zuugle.si always in Slovenian.

Additionally we should think about doing #178 (https://github.com/orgs/bahnzumberg/projects/2/views/13?pane=issue&itemId=37797710)
