### ISSUE TITLE
Start Frontend with www2 as Backend

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#169]
I would like to run "npm run start-remote-api". This should do the same as "npm run start", so that I can develop locally. The only difference should be, that the backend on UAT environment is used: www2.zuugle.at
This way I do not have to install the zuugle-api.

**Comment by tobHai** [comment]
I will have a look at it this week (probably on the weekend)

**Comment by tobHai** [comment]
Committed an idea for a  solution. 
Backend calls are already working, but I still need to investigate loading of gpx files etc.

**Comment by tobHai** [comment]
Loading GPX files from www2.zuugle.at from localhost is currently not possible due to CORS restrictions:
`Access to XMLHttpRequest at 'https://www2.zuugle.at/public/gpx/bahnzumberg_426.gpx' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by martinheppner** [comment]
Unfortunately I have no experience with CORS. :-( 
What does "adapt Access-Control-Allow-Origin" mean? The line "Access-Control-Allow-Origin" is nowhere in our current code.

**Comment by tobHai** [comment]
Per default a browser does not allow a "cross-origin" request, e.g. the zuugle suchseite running on `localhost:3000` cannot request data from `www2.zuugle.at/public/some-file-path`  without a special configuration.
The server serving the files under  `www2.zuugle.at/public/some-file-path`  has to add a special CORS header. This header is then checked by the browser and if properly set, the JS code running in the browser can fetch data from another origin (in this case `www2.zuugle.at`).  

I believe the `zuugle-api` project is responsible for serving the files under `/public/some-file-path`.  
Since `zuugle-api` is using the `express` framework we can enable CORS by adding a middleware:  https://expressjs.com/en/resources/middleware/cors.html

**Comment by FALBZB** [comment]
Hi Tobias, not sure if you are aware of this,  cors module is already being imported and used in the server file index.js in API, and CORS configuration is defined in the file zuugleCors.js along with a white list, this list already contains www2.zuugle.at.

**Comment by tobHai** [comment]
Thanks for the hint @FALBZB. I did check the CORS configuration of the API project now, and I think it is just lacking the CORS config for the static asset path: 
https://github.com/bahnzumberg/zuugle-api/blob/fd7e78531dfb26dbfbb3e5d2f06bf78d3b519f01/src/index.js#L34 
For static file access an empty CORS config is used. 
I believe we could simply pass in the same CORS options here as well, and then it should be possible to use the deployed API locally as well.

**Comment by tobHai** [comment]
Hi @martinheppner. 
I added the CORS config for the static file access as well here: 
https://github.com/bahnzumberg/zuugle-api/tree/config-for-uat-as-backend

Can you maybe deploy this branch to www2.zuugle.at? And test it together with this branch: https://github.com/bahnzumberg/zuugle-suchseite/tree/config-for-uat-as-backend
By running `npm run start-remote-api` ? 

I cannot test it properly without the deployment to www2.zuugle.at unfortunately.

**Comment by martinheppner** [comment]
I deployed the changes on api to UAT. It works on my local development environment by running "npm run start-remote-api" as seen on the screenshot below. The search seems to work, just the images are not showing. But the fall back images show.

![image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/b11b0944-19cd-4419-9cc3-74c7eb781299)

**Comment by martinheppner** [comment]
In the moment this is working sufficiently, we can establish a next step: Automated testing of the frontend. :-)

**Comment by tobHai** [comment]
Thanks for the deployment. I will analyze it further.

Main page seems to work for me (showing different images?):
![image](https://github.com/bahnzumberg/zuugle-suchseite/assets/37791246/f055bb7c-c90f-43d4-9bd4-07f5d618ed36)
And I can see in the DevTools that some images are loaded from www2.zuugle.at:
![image](https://github.com/bahnzumberg/zuugle-suchseite/assets/37791246/0caf1e4e-42cd-4185-913a-e098b6944dbc)
However, I'm receiving some 404 errors from e.g.: `
https://www.bahn-zum-berg.at/wp-content/uploads/2021/08/Tour_45_Titelfoto_Kaasgrabenkirche_2_Regina_Hrbek-scaled-720x480.jpg`. 

And the tour detail page fails with a network error. I will analyze it further.

**Comment by martinheppner** [comment]
The images which are loaded from bahn-zum-berg.at (or not, if not available), are ok. The images, which are showing maps are coming from Zuugle.

**Comment by tobHai** [comment]
@martinheppner I just pushed a new configuration, please fetch the latest changes and deploy again - thanks!
