### ISSUE TITLE
log menu_lang and country_code

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#18]
**menu_lang** is two characters long. It defines the language the visitor gets the surface, the menu shown in. 
It can be one of these values: de, ch, fr, it, sl 
(Attention! sl = SL)

**country_code** is two characters long. It defines the top level domain.
It can be one of these values: AT, DE, CH, FR, IT, SL
The country code is stored as UPPER carachters in the database, to distinguish the value from menu_lang.

Both values should be logged with each search of the user into the table "logsearchphrase". The click on a detail page for one hike, should not be logged there.
The existing comlumns should continue to be filled.

After this issue #17 can be implemented.

**Comment by martinheppner** [comment]
Tours.js in line 262 "const sql = `INSERT INTO logsearchphrase"

**Comment by Falsal** [comment]
Q1: 
so, menu_lang is one of de, ch, fr, it, sl
is "ch" a language ?

**Comment by Falsal** [comment]
the basic functionality is done, but there are related issues that we must agree on.
 so :
**on the client side** , I am pulling the currLanguage inside loadTours.js in every exported function that returns a function loadList() . In crudActions.js , added "language" in the arguments of the function then initialized it and then passed it as a param to the axios call.
**On the backend side** I have pulled out the language from the request :  req.query.currLanguage , initialised it and add to the sql query which is then passed as a knex raw call.
I had to take out the condition which was based on "search" not being undefined, this is because 'search' value (which is supposed to be the value from the input of search bar) is not reaching this line yet.

**result:** 
now the insert in table "logsearchphase" happens 2 times 

**next steps:**
must get input bar done before we then make sure it is arriving to the backend where "search" value is set.

So I will consider this issue complete and will move on to the client side related issue, so i can create the input in search bar.

**Comment by Falsal** [comment]
next steps:
must agree on what conditions this table insert must occur. 
at the moment, every click on go button would cause an insert inside the table "logsearchphrase"

My opinion: 
just before the call for insertion , check if the values have been added already using localStorage . (check search value)
