### ISSUE TITLE
indexMainTranslate.js needed?

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#198]
Is the file zuugle-suchseite\src\translations\indexMainTranslate.js needed? I think it is only the global i18n config, which is still needed.

**Comment by FALBZB** [comment]
yes true, since we are not using i18n for the translation of the index.html then we can delete both the original and the copy, as long as we can get back to them in our repo somehow.

by the way , both these files could be useful one day, It took some effort to do it, also there is a slightly different approach in the " indexMainTranslate_copy".
