### ISSUE TITLE
Mountain range link not filtering correctly

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#204]
The screenshot below shows the result page of www.zuugle.si/waldviertel

But the shown tours are not filtered on Waldviertel. They seem not to be filtered at all.

Is it possible, that these pages are dependent on the old search parameter?

![Screenshot_20230920_015118_Chrome.jpg](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/6e40781b-0fd8-4d48-83a6-720e3cad1ed2)

**Comment by FALBZB** [comment]
@martinheppner : 
when i use the links on the start page to find the tours for these ranges i do get them, here is a generated url from such a search:
https://www.zuugle.si/suche?range=Dachsteingebirge&city=ljubljana

here is a screenshot of the result:


![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/139218009/6ce1f480-388c-4bc3-8103-5ea40e27765d)

Is the link you have provided here [www.zuugle.si/waldviertel](http://www.zuugle.si/waldviertel) your own ? why is there no "suche?" in it ?

**Comment by martinheppner** [comment]
1. On start page www.zuugle.at click on Rätikon
![image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/1baee15d-3943-46fe-8974-e7320247ec22)

2. Page shows Rätikon - results are from Wienerwald
![image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/8637a4d6-c9d4-41c3-b7b3-d23f5f1c06dd)

**Comment by FALBZB** [comment]
@martinheppner :
I switched the url creation to be using our normal url params designation, so it is pulling the city param and any provider param.

I have one remark and one question:
Question:
why are you returning an empty array inside listAllRangeLinks? i mean this one:
if (link == "null") {
                return [];
            }

I can understand that you return an empty string or "N/A" as in link not available . Because the return in this case will just move to the next value in the array as the map function continues iterating over the array values, so if we ever get such a case expect to get an error.

**Comment by FALBZB** [comment]
@martinheppner 
we have an issue with the range parameter, once you select it there is no way to erase it from the parameter of the url unless you do it manually. What would be your suggestion ?
