### ISSUE TITLE
Remove valid_thru field and stop using it

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#256]
Remove all the use of the field "valid_thru". Once it is not used in the frontend, please create a ticket in the api repository, so it is removed there as well (as the last task of this issue).

**Comment by Falsal** [comment]
for the record:

suchseite: "valid_through' , cannot be found when searched, it is because this value is used only as a condition for a search inside the api when creating the array of valid connections (this is done inside two functions: " getReturnConnectionsByConnection" and "connectionsExtendedWrapper"

**Comment by martinheppner** [comment]
So there is nothing to be done on Suchseite? This means we can create a ticket to remove it from API?

**Comment by Falsal** [comment]
yes, will do that now
