### ISSUE TITLE
Enable bookmarking

### ISSUE THREAD

**Issue by TheKashe** [bahnzumberg/zuugle-suchseite#279]
As a user, I want to be able to bookmark tours (deep link directly to a tour), which currently doesn't seem to be possible.

The amount of tours on the site is huge, which leads to decision fatigue when it comes to planning where to go on a weekend. So I want to have a list of curated candidate tours stored in my bookmarks and then use those to decide where to go.

My first attempt was using the share link (which creates uuid), only to have realized with horror that links are invalid the next week and don't work anymore, hence all my effort was lost.

My second attempt was creating a script for appending tourId to url and injecting that to localStorage. Again, happy to have a list of curated tours, only to realize right now that tourId is not immutable(!?), and my stored ids are invalid just 2 days after I have bookmarked them.

I'm happy to contribute to a solution, but then looking at the zuugle-api project, the import-data-full job assumes I have access to mysql DB with all tour data, which is not mentioned anywhere.

**Comment by martinheppner** [comment]
Hi, thank you for pointing out to me the other ticket with the names and mail adresses. I deleted it now.

To your question here: We discussed this in depth. Of course we are able to produce permanent links. We decided against it, because the itinerary is changing frequently. This includes the daily changing itinerary, but also the seasonal change: From one day to another a tour can not be reachable via public transportation, because the cable car or the bus, is not operating for a service break, or because of winter season.

Regarding your desired/proposed feature: I believe this would be a great feature, but I would like to integrate it into the application. Meaning: Users log in with email and password and can store their favorite tours. 

What do you think?

**Comment by TheKashe** [comment]
For me personally, the changing itinerary is a non-issue; I understand it's not constant that's why I call it "curated candidate list". Depending on the weather, timetable etc., a tour might be feasible or not.

Long term, I think login with some kind of credentials is OK and opens new opportunities, such as the ability to provide comments, ratings, photos etc. 

One real downside I can think of is that without immutable IDs, it will still be impossible to reliably share a tour with friends or with family; specially the later is important in case something goes wrong, so people know where to look for you.

In addition, I'm afraid that adding this functionality in the portal itself requires considerably more effort, and I need to figure out a solution for me soon :)

**Comment by martinheppner** [comment]
The ultimate cause, why we do not provide a stable link is, that we do not own the tours. All the portals are putting in a lot of effort to provide the content. We do not want to take the traffic away from them. Sharing a tour is possible right now for 8 days until it's invalid. Login and having favourites would be ok. Anything else would endanger the cooperation of the sources we are getting the tours from.
