### ISSUE TITLE
Enable dev.zuugle

### ISSUE THREAD

**Issue by Falsal** [bahnzumberg/zuugle-suchseite#282]
Currently this created subdomain is not working . Outsource to Fiverr expert the job of making this new production environment work. 

Request : 
Title : Fix a bug in a deployment Nginx and PM2 environment including a follow-up mentoring session

Description: 
The attempt is being made to enable a subdomain inside an already-working domain to function. Currently it is giving a status of 500 (Internal Server Error).
Stack:
Application: Frontend in Reactjs (v18) , Backend server : Nodejs (20.3.0) and Express 
Deploy Environment : Nginx, PM2.

When The job is completed an online mentoring session of 1,5 hours is required for a member of our team.

**Comment by martinheppner** [comment]
The attempt has made to enable an additional subdomain (https://dev.zuugle.at) to an already working subdomain (https://www2.zuugle.at) to work. Currently it is giving a status of 500 (Internal Server Error).

DNS settings & certificate are setup. The problem is probably between ngninx and the pm2 routing to appropriate ports, which are not conflicting with the working UAT environment on www2.zuugle.at

Application: Frontend in Reactjs (v18) , Backend server : Nodejs (20.3.0) and Express
Deploy Environment : Nginx, PM2.

When The job is completed an online mentoring session of 1,5 hours is required for a member of our team.

**Comment by martinheppner** [comment]
Martin will make a call with Simon Pablo and Carlos (Fiverr)

**Comment by martinheppner** [comment]
dev/server.js is now running on port 7500
