### ISSUE TITLE
Itinerary detail 1: w/o 4 columns

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#285]
![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/87718607/2ee69fac-88cf-4dfd-af12-b91a5f1ef098)

Switching itinerary details to JSON from 4 columns

**Comment by martinheppner** [comment]
The table "Fahrplan" has been altered. The folowing columns have been added:

'connection_description_json',
'connection_lastregular_arrival_stop',
'connection_lastregular_arrival_stop_lon',
'connection_lastregular_arrival_stop_lat',
'connection_lastregular_arrival_datetime',
'return_description_json',
'return_firstregular_departure_stop',
'return_firstregular_departure_stop_lon',
'return_firstregular_departure_stop_lat',
'return_firstregular_departure_datetime'

The functionality of the two JSON columns are descibed here: https://github.com/bahnzumberg/hermes/wiki/Connection-and-Return-Description
The JSONs allow us to translate all elements like "Zug" or "Bus", etc.

The others are needed for the itinerary as well.

Please enhance the api towards the surface (suchseite), so we can implement the additional functionality.

**Comment by Falsal** [comment]
Job for this issue is completed but we need testing without removing the columns at this time because pdf creation is still using it. 
On the other hand; according to a review of the api code today, it seems that the switch to JSON for the pdf creation (and inside tours.js) should not take more than  a day. So my suggestion is to do that as a second step and we could then test the two issues by removing the columns.

**Comment by martinheppner** [comment]
That sounds amazing!
