### ISSUE TITLE
Code elimination in Search.js

### ISSUE THREAD

**Issue by FALBZB** [bahnzumberg/zuugle-suchseite#80]
Purpose: 
with the advent of the new design we do not use things like : region, state, country etc. , these were previously part of the params that have been sent from start page.
so we should go through some code inside Search to check if we keep it or delete it, discuss also the consequences if any regarding such action.

**Comment by martinheppner** [comment]
In general I am completely with you, when we talk about removing unused code!

Regarding state and country information, I am hesitating. We can introduce a filter on country and on state, because people have the ticket "Klimaticket Salzburg" and want only to see hikes, which are in Salzburg. So they will filter on Salzburg.

Bottom line: I would leave state and country as it is at the moment for future use.

**Comment by FALBZB** [comment]
Ok, fine will leave these two, but in any case , let's still do the check
in a call on Thursday. I sent you an invitation already.
